# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_data": "00_core.ipynb",
         "make_experiment": "00_core.ipynb",
         "model": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://erlenman.github.io/nbdev_test/"

git_url = "https://github.com/erlenman/nbdev_test/tree/master/"

def custom_doc_links(name): return None
