# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'say_hello_back', 'here_will_be_dragons']

# Cell
# exports
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

def say_hello_back(to):
    "Say hello to somebody"
    return f'Hello you too!'

def here_will_be_dragons():
    'Anything is possible'
    return True